# Generated by Django 2.0.2 on 2018-03-10 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='image',
            field=models.CharField(max_length=100),
        ),
    ]
